name: FreedomBot
main: com.FoxIshDaBest.FreedomBot.FreedomBot
version: 1.3
author: FoxIshDaBest
softdepend: [TotalFreedomMod]

commands:
    freedombot:
      description: 'Displays FreedomBot Information.'
      usage: /<command>
      
    admintools:
      description: 'Send a message to all online administrators.'
      usage: /<command>
      
    opme:
      description: 'Op yourself.'
      usage: /<command>